### ISSUE TITLE
schema "raster" does not exist

### ISSUE THREAD

**Issue by edzer** [hunzikp/velox#4]
when trying to run your benchmark, I get:
```r
> ## Import raster into PostGIS and index
> dbSendQuery(con, "DROP TABLE IF EXISTS raster.large;")
NOTICE:  schema "raster" does not exist, skipping
```

**Comment by edzer** [comment]
Well, I uncommented a few of these statements, set `bench=TRUE`, but then get
```r
Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  relation "raster.large" does not exist
LINE 4:               FROM raster.large,
                           ^
)
Calls: benchmark ... dbSendQuery -> dbSendQuery -> postgresqlExecStatement -> .Call
Execution halted
```

**Comment by hunzikp** [comment]
The PostgreSQL NOTICE is harmless; the 'DROP .. IF EXISTS' statement triggering it is just a precautionary measure. The second error indicates that uploading the raster data to the PostGIS DB using the raster2pgsql utility must have failed. That may have been caused by the fact that the script used my username (hunzikp) when requesting the upload in a static manner. I've addressed this in two ways: You can now easily opt out of the PostGIS part of the benchmarking procedure using the TEST_PGIS boolean. You can also set your PostgreSQL username and password at the very beginning in a consistent manner. Would you try again with the new script? Thx.

**Comment by edzer** [comment]
Thanks, all runs well now, can confirm your outcomes.
